language: node_js
dist: xenial
nodejs: 
    - 10
    - node  #latest stable Node.js release
    - lts/* #latest LTS Node.js release

arch:
   - amd64
   - ppc64le   

addons:
   apt:
    update: true
    packages: 
       - build-essential 
       - npm 
       - wget
 
